# Generated by Django 2.1.7 on 2020-06-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('comptoir', models.CharField(max_length=10)),
                ('table', models.IntegerField()),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comptoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('bars', models.IntegerField()),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('table', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Contact')),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comptoir',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='reference', to='api.Reference'),
        ),
    ]
