# Generated by Django 2.1.7 on 2020-06-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
