# Generated by Django 2.1.7 on 2020-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200610_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptoir',
            name='reference',
        ),
        migrations.AddField(
            model_name='comptoir',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='api.Stock'),
        ),
    ]
